update kurbeScrip

diff --git a/messaging_app/kurbeScript b/messaging_app/kurbeScript
--- a/messaging_app/kurbeScript
+++ b/messaging_app/kurbeScript
@@ -1,6 +1,13 @@
 #!/bin/bash
-
 set -e
+
+# Check if minikube is installed; if not, download it
+if ! command -v minikube &> /dev/null; then
+    echo "Minikube not found. Downloading..."
+    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
+    chmod +x minikube
+    sudo mv minikube /usr/local/bin/
+fi
 
 echo "Starting Minikube cluster..."
 minikube start
